### ISSUE TITLE
EDK project template files

### ISSUE THREAD

**Issue by skoroneos** [sprocket-fpga/fpga_miner#1]
Hi.
Do you have any project templates to be used on the xilinx EDK to build additional bitstreams ?

**Comment by sprocket-fpga** [comment]
I just use Vivado.  I haven't used the EDK to creating any bitstreams.

**Comment by skoroneos** [comment]
Could you post them ? I am trying to understand what is need to make a "compatible" bitstream (in terms of comm protocol etc).
